### ISSUE TITLE
Plugin: Shadertoy Search/Import

### ISSUE THREAD

**Issue by 2xAA** [vcync/modV#170]
- [x] Createa plugin to search and import Shadertoy Shaders using their API: https://www.shadertoy.com/api
- [ ]  Add iMouse default controls to every imported shader
- [ ] Save the loaded shader into a preset

**Comment by TimPietrusky** [comment]
This would be the best thing

**Comment by 2xAA** [comment]
Work started here https://github.com/2xAA/modV/tree/2.0-plugins

**Comment by 2xAA** [comment]
Good Shadertoy implementation and example of shader code here https://github.com/minoru-ito/ShadertoyRenderer/blob/master/src/shadertoyRendererNode.cs

**Comment by TimPietrusky** [comment]
It would also be nice to save an imported Shadertoy shader into the project / preset, so that it can be used also after reloading modV.

**Comment by 2xAA** [comment]
Yes this would be good - some work on the Media Manager needs to be done to facilitate this I think.

Another feature which would be good for Shader Toy importing would be the ability to "scrape" variables in the shader and present them to the user via some sort of UI, to turn them into uniforms which can be written to by module's prop inputs.

**Comment by TimPietrusky** [comment]
@2xAA I summarised our discussion:

Automatically transform the iMouse props into 4 different controls, because all shader support that. 

```
vec4 iMouse = vec4(mX*RENDERSIZE.x, mY*RENDERSIZE.y, mZ*RENDERSIZE.x, mW*RENDERSIZE.y);
```

https://github.com/vcync/modV/blob/7009b56049bf9c13d97c5960df939fc53b12ae66/src/extra/shadertoy/Gallery.vue#L68 has to be extended like this

```js
modV.register({
  meta: {
    name: result.info.name,
    author: result.info.username,
    version: 0.1,
    uniforms: {},
    type: 'shader',
    previewWithOutput: true,
    flipY,
  },
  fragmentShader: `vec4 iMouse = vec4(mX*iResolution.x, mY*iResolution.y, mZ*iResolution.x, mW*iResolution.y);\n\n${code}`,
  props: {
    mX: {
      type: 'float',
    },
    mY: {
      type: 'float',
    },
    mZ: {
      type: 'float',
    },
    mW: {
      type: 'float',
    },
  },
});
```

And we have to update https://github.com/vcync/modV/blob/2.0/src/modv/renderers/shader.js and remove the iMouse (and maybe more changes)

**Comment by TimPietrusky** [comment]
The *Import* of this feature is very important to get over the problems introduced in #331, because saving a Shadertoy shader into a preset will now make it impossible to load a preset, as the shader is not saved into the local file system. 

In the meantime it's also possible to do this manually by using the snippet of https://github.com/vcync/modV/pull/332#issuecomment-478365690
