### ISSUE TITLE
Presets don't load/save correctly

### ISSUE THREAD

**Issue by 2xAA** [vcync/modV#27]
Image and Video Controls lose their source.
Palette Controls lose the loaded colours, BPM and timing settings also.

**Comment by TimPietrusky** [comment]
When saving two text modules into a preset, then restarting modV and loading back the preset, the second text module is gone. 

When you assign MIDI controls to the second Text (the one that is gone after loading the preset) and add the Text manually back in, the MIDI assignments still work.

**Comment by 2xAA** [comment]
modV really needs a suite of tests to prevent this happening again.

Vue recommends either Karma or Jest for this. Jest seems well documented compared to Karma, though I don't have experience in test writing.

@TimPietrusky - can you recommend anything?

**Comment by TimPietrusky** [comment]
I used Karma and Jest before. In luminave I use the stuff that comes with the https://polymer.github.io/pwa-starter-kit/application-testing:

- Unit-tests with mocha
- Integration-tests with mocha + [puppeteer](https://github.com/GoogleChrome/puppeteer) 

So I would say it doesn't really matter, we can choose whatever we want. But I would suggest having both unit and integration tests. And it's worth to look into what the pwa-starter-kit is doing, because we can borrow a lot from them.

**Comment by TimPietrusky** [comment]
It's really annoying that loading a palette is not working at all:

- Is not loading from the preset
- When I load a saved palette into for example "Text", it just loads the amount of colors, but not the saved colors (if the color is white, it doesn't load, if the color is black, it loads the colors, but doesn't indiciate in the UI that this was succesful)
