### ISSUE TITLE
Plugin: Value Expression should load/save assignments from/to presets

### ISSUE THREAD

**Issue by 2xAA** [vcync/modV#279]
The title.

**Comment by TimPietrusky** [comment]
I think this is not working, because when I use an expression on any property, the value is restored from the preset, but not represented in what is rendered on the canvas. 

## Steps to reproduce
* Put the Text module into the layer
* Add an expression to the size property like "value * 3"
* Set the sitze to 300
* Save the preset into "test text"
* Reload modV
* Load the "test text" preset
* See that the size + expression are loaded, but the rendered Text is still as small as it is when you load the Text module the first time
