### ISSUE TITLE
Why is the stroke of the Waveform 2.0 limited to 30?

### ISSUE THREAD

**Issue by TimPietrusky** [vcync/modV#308]
I'm trying to figure out why the max value for stroke on the Waveform 2.0 is limited to 30? Because I want to have a higher value so I had to change the code (using an expression was not working). 

But why is this limited in the first place?

**Comment by 2xAA** [comment]
https://github.com/vcync/modV/blob/2.0/src/modv/sample-modules/Waveform-2.0.js#L19

It is using a `strict` prop because using a negative value for Canvas2D's strokeWidth causes an error to be thrown.

This could actually be removed and `abs` be set to true on that prop instead. `abs` was added later than `strict` so it's a legacy thing.

`strict` keeps values within the set ranges at all costs, but `abs` will just restrict the value to be an absolute value.

If you want to make a PR to change this, that would be great!

**Comment by TimPietrusky** [comment]
Speaking of strict, might this also be related to #307? I have to check if my problems are gone.

**Comment by 2xAA** [comment]
I don't think it would be related to #307, the Shader and ISF modules have no limits set on them by default as there's no error to be thrown in GLSL.

**Comment by 2xAA** [comment]
Closing as the question has been answered.
