### ISSUE TITLE
[preset] Loading disabled "inherit" not working

### ISSUE THREAD

**Issue by TimPietrusky** [vcync/modV#469]
**Operating system and application version**
 - OS: macOS
 - Version: next

**Describe the bug**
When loading a preset where the group property `inherit` is set to `false`, the value will be set to `true` automatically. 

**To Reproduce**
1. Disable `inherit` for a group
2. Save the preset
3. Refresh modV
4. Load the preset
5. See that `inherit` is enabled for the group

**Expected behavior**
`inherit` is loaded correctly from the preset.

**Additional context**
In the preset the value for `inherit` is set correctly to `false`.

**Comment by TimPietrusky** [comment]
@2xAA Why do we need to set the default of `inherit = -1` in https://github.com/vcync/modV/blob/main/src/application/worker/store/modules/groups.js#L122? Can't we just get rid of this and set a proper default somewhere else? 

Also when loading the preset, `args.inherit: false` will always produce `-1`.

**Comment by 2xAA** [comment]
Inheritance isn't fully compatible with modV 2 yet, which is why `-1` is there - it's leftover from modV 2's code.

`-1` is there as modV 2 allowed inheriting from a target group rather than just the previous group in the list.
We need to set a default in case presets are malformed in some way.

But yes you're right, that's a bug and we should change this to check for `undefined` rather than falsy.

In the future that will either be false or the ID of a Canvas from `store.state.outputs.auxillary`.

**Comment by TimPietrusky** [comment]
So are we doing this to be able to load modV 2 presets into modV 3?

**Comment by TimPietrusky** [comment]
And isn't that why we have `inheritFrom`? Why is `inherit` (which is used to activate inheritance) used for the same purpose?

**Comment by TimPietrusky** [comment]
Yeah so `inheritFrom` should be used, but this is not implemented. So we "just" fixed loading the `inherit` for now which was the main problem from this ticket.
